#!/usr/bin/env python3
"""
chorus-pdf extraction script — images mode (--images)
Generated by chorus-pdf skill
Sandbox : test-02-construction-corpus-en-pdf
Source  : corpus/002-uk-approved-doc-a-2013.pdf
Output  : corpus/004-uk-approved-doc-a-2013-vision.md
Pages   : 54
DPI     : 150

Note: PDF uses Form XObjects (vector diagrams) — pdfminer LTFigure detection
      is unreliable on this document (finds only decorative full-page watermarks).
      Images mode (pdftoppm full-page render) is the correct approach.
"""

import sys
import base64
import json
import glob
import re
import time
import tempfile
import subprocess
import urllib.request
import urllib.error
import os

PDF_PATH    = "/home/civorra/Documents/Chorus/sandboxes/test-02-construction-corpus-en-pdf/corpus/002-uk-approved-doc-a-2013.pdf"
OUTPUT_PATH = "/home/civorra/Documents/Chorus/sandboxes/test-02-construction-corpus-en-pdf/corpus/004-uk-approved-doc-a-2013-vision.md"
CHUNK_SIZE  = 5
DPI         = 150
MAX_RETRIES = 4
API_KEY     = os.environ.get("ANTHROPIC_API_KEY", "")
API_URL     = "https://api.anthropic.com/v1/messages"

PROMPT = """You are a technical document extraction engine.
Your task is to produce a complete, faithful plain-text reconstruction of this PDF page.

Apply the following rules strictly:

TEXT
- Extract all text in reading order (top to bottom, left to right).
- For multi-column layouts: extract column 1 fully, then column 2. Insert a blank line between columns.
- Preserve section numbers, article numbers, and clause references exactly as printed.
- Preserve all footnote markers and footnote text (append footnotes at end of page output).
- Do not summarize, paraphrase, or omit any text.

TABLES
- Reconstruct every table in Markdown format (pipe syntax).
- Preserve all column headers, row labels, units, and footnote references inside the table.
- If a table spans multiple pages: output the fragment visible on this page; prefix it with
  [TABLE CONTINUED — <table title or number>] if this is a continuation.

FIGURES AND DIAGRAMS
- For every figure, diagram, or illustration: output a block of the form:
    [FIGURE <N> — <title or caption>]
    <Structured description of all visual content:>
    - Labeled dimensions, dimensions with units
    - Named components and their spatial relationships
    - Numerical values visible in or next to the figure
    - Arrows, load paths, connection points, hinge symbols, support symbols
    - Hatching patterns and what material or condition they represent
    - Scale bar if present
    [END FIGURE <N>]
    IDENTIFIERS: ["<id1>", "<id2>", ...]
- If there is no figure number or caption in the PDF, assign [FIGURE ?] and describe anyway.
- For IDENTIFIERS: list every alphanumeric code, label, designation or identifier
  visible in the figure (callout tags, part numbers, zone codes, element IDs,
  article references, dimension labels with letters). Use the exact string as printed.
  Exclude purely numeric values (dimensions, measurements), single letters used as
  generic variables, and common stopwords. Output valid JSON array on a single line
  immediately after [END FIGURE <N>]. Output [] if no identifiers found.

EQUATIONS AND FORMULAS
- Render every equation in linearized form (e.g., S = V × O × A).
- Preserve all variable names, subscripts, and units as printed.

HEADERS AND FOOTERS
- If a page has a running header or footer containing normative information (standard number,
  edition date, section title): include it once at the top of the page output as:
    [HEADER: <content>]
- Omit purely decorative headers/footers (page number alone, logo only).
- Omit watermarks like "ONLINE VERSION".

OUTPUT FORMAT
- Begin each page with: === PAGE <N> ===
- End each page with: === END PAGE <N> ===
- Separate pages with a single blank line.
- Use UTF-8. Preserve all special characters (±, ≤, ≥, ×, °, ², ³, φ, σ, …).
- Do not add commentary outside the === PAGE === markers.
"""


def render_pages(pdf_path, tmpdir):
    """Render all PDF pages to PNG files using pdftoppm."""
    prefix = os.path.join(tmpdir, "page")
    result = subprocess.run(
        ["pdftoppm", "-r", str(DPI), "-png", pdf_path, prefix],
        capture_output=True
    )
    if result.returncode != 0:
        raise RuntimeError(f"pdftoppm failed:\n{result.stderr.decode()}")
    pages = sorted(glob.glob(os.path.join(tmpdir, "page-*.png")))
    if not pages:
        pages = sorted(glob.glob(os.path.join(tmpdir, "page.*.png")))
    if not pages:
        raise RuntimeError("pdftoppm produced no PNG files")
    return pages


def image_to_b64(path):
    with open(path, "rb") as f:
        return base64.standard_b64encode(f.read()).decode("utf-8")


def call_claude(page_paths, page_offset):
    """Send a chunk of page PNGs to Claude vision."""
    content = []
    for i, path in enumerate(page_paths):
        page_num = page_offset + i + 1
        content.append({
            "type": "text",
            "text": f"[Processing page {page_num}]\n\n{PROMPT}"
        })
        content.append({
            "type": "image",
            "source": {
                "type": "base64",
                "media_type": "image/png",
                "data": image_to_b64(path)
            }
        })

    payload = {
        "model": "claude-opus-4-5",
        "max_tokens": 8192,
        "messages": [{"role": "user", "content": content}]
    }
    headers = {
        "x-api-key": API_KEY,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json"
    }
    label = f"{page_offset+1}-{page_offset+len(page_paths)}"
    for attempt in range(MAX_RETRIES):
        req = urllib.request.Request(
            API_URL,
            data=json.dumps(payload).encode("utf-8"),
            headers=headers,
            method="POST"
        )
        try:
            with urllib.request.urlopen(req, timeout=300) as resp:
                return json.loads(resp.read().decode("utf-8"))["content"][0]["text"]
        except urllib.error.HTTPError as e:
            body = e.read().decode("utf-8", errors="replace")
            if e.code in (429, 529) and attempt < MAX_RETRIES - 1:
                wait = 10 * (2 ** attempt)
                print(f"  HTTP {e.code} — retrying in {wait}s ...", file=sys.stderr, flush=True)
                time.sleep(wait)
            else:
                raise RuntimeError(f"HTTP {e.code} on pages {label}: {body[:500]}")
        except Exception as e:
            if attempt < MAX_RETRIES - 1:
                wait = 10 * (2 ** attempt)
                print(f"  ERROR {e} — retrying in {wait}s ...", file=sys.stderr, flush=True)
                time.sleep(wait)
            else:
                raise


def split_page_markers(text, expected_pages):
    """Parse Claude's response into {page_num: page_block}."""
    result = {}
    matches = list(re.finditer(
        r'(=== PAGE (\d+) ===.*?=== END PAGE \d+ ===)', text, re.DOTALL
    ))
    if matches:
        for m in matches:
            pnum = int(m.group(2))
            result[pnum] = m.group(1)
    else:
        result[expected_pages[0]] = (
            f"=== PAGE {expected_pages[0]} ===\n{text.strip()}\n"
            f"=== END PAGE {expected_pages[0]} ==="
        )
    for p in expected_pages:
        if p not in result:
            result[p] = (
                f"=== PAGE {p} ===\n"
                f"[WARNING: page {p} not found in Claude response]\n"
                f"=== END PAGE {p} ==="
            )
    return result


def main():
    if not API_KEY:
        print("⛔ ANTHROPIC_API_KEY not set", file=sys.stderr)
        sys.exit(1)

    print("[chorus-pdf] Images mode — rendering all pages via pdftoppm ...", file=sys.stderr, flush=True)

    results = {}
    with tempfile.TemporaryDirectory(prefix="chorus-pdf-") as tmpdir:
        all_pages = render_pages(PDF_PATH, tmpdir)
        total = len(all_pages)
        print(f"[chorus-pdf]   → {total} pages rendered at {DPI} DPI", file=sys.stderr, flush=True)

        chunks = [
            all_pages[i:i+CHUNK_SIZE]
            for i in range(0, total, CHUNK_SIZE)
        ]
        print(f"[chorus-pdf]   → {len(chunks)} chunk(s) of {CHUNK_SIZE} pages", file=sys.stderr, flush=True)

        for cidx, chunk in enumerate(chunks, 1):
            page_offset = (cidx - 1) * CHUNK_SIZE
            start_p = page_offset + 1
            end_p   = page_offset + len(chunk)
            print(f"[chorus-pdf] Chunk {cidx}/{len(chunks)} — pages {start_p}–{end_p} ...",
                  file=sys.stderr, flush=True)
            response = call_claude(chunk, page_offset)
            parsed   = split_page_markers(response, list(range(start_p, end_p + 1)))
            results.update(parsed)
            chars = sum(len(t) for t in parsed.values())
            print(f"[chorus-pdf]   → {chars} chars extracted", file=sys.stderr, flush=True)

    parts = [results[p] for p in sorted(results)]
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n\n".join(parts))
    print(f"[chorus-pdf] ✅ Written to {OUTPUT_PATH}", file=sys.stderr, flush=True)


if __name__ == "__main__":
    main()
