#!/usr/bin/env python3
"""
chorus-pdf extraction script — text mode (default)
Generated by chorus-pdf skill
Sandbox : 11-cyber-sec
Source  : normes/etsi/etsi-TS-119-312.pdf
Output  : corpus/009-etsi-ts-119-312-text.md
"""

import sys
import os

try:
    import pdfplumber as _chk; del _chk
except ImportError:
    _pipx_py = os.path.expanduser("~/.local/share/pipx/venvs/pdfplumber/bin/python3")
    if os.path.exists(_pipx_py) and sys.executable != _pipx_py:
        os.execv(_pipx_py, [_pipx_py] + sys.argv)

PDF_PATH    = "/home/civorra/Chorus/sandboxes/11-cyber-sec/normes/etsi/etsi-TS-119-312.pdf"
OUTPUT_PATH = "/home/civorra/Chorus/sandboxes/11-cyber-sec/corpus/009-etsi-ts-119-312-text.md"

FIGURE_PLACEHOLDER = (
    "[FIGURE — not extracted]\n"
    "[Run chorus-pdf with --hybrid, --auto or --images to extract figures via LLM vision]"
)


def detect_table_columns(page):
    edges   = page.edges
    v_edges = [e for e in edges if e['orientation'] == 'v' and e['height'] > 30]
    h_edges = [e for e in edges if e['orientation'] == 'h' and e['width']  > 50]
    if len(h_edges) < 2 or len(v_edges) < 1:
        return None
    xs = sorted(set(e['x0'] for e in v_edges))
    clustered = []
    for x in xs:
        if not clustered or x - clustered[-1] > 3:
            clustered.append(x)
    widest = max(h_edges, key=lambda e: e['width'])
    all_xs = sorted(set([widest['x0']] + clustered + [widest['x1']]))
    return all_xs if len(all_xs) >= 2 else None


def extract_tables_from_page(page):
    col_xs = detect_table_columns(page)

    def cell(c):
        return str(c or "").replace("\n", " ").replace("|", "｜").strip()

    def quality_check(rows):
        if not rows or not any(any(c for c in row) for row in rows):
            return False
        total_cells = sum(len(row) for row in rows)
        empty_cells = sum(1 for row in rows for c in row if not str(c or "").strip())
        if len(rows[0]) == 1:
            long_texts = sum(1 for row in rows for c in row
                            if c and len(str(c).strip()) > 100)
            if total_cells > 0 and long_texts / total_cells > 0.30:
                return False
        if total_cells > 0 and empty_cells / total_cells > 0.55:
            return False
        non_empty_cells = [str(c or "").strip() for row in rows for c in row
                           if str(c or "").strip()]
        if non_empty_cells:
            fragments = sum(1 for t in non_empty_cells
                            if len(t) < 20 and t and t[0].islower())
            if fragments / len(non_empty_cells) > 0.30:
                return False
        if len(rows[0]) > 1 and total_cells > 0 and empty_cells / total_cells > 0.40:
            return False
        return True

    def format_table(rows):
        if not rows:
            return None
        lines = []
        lines.append("| " + " | ".join(cell(c) for c in rows[0]) + " |")
        lines.append("| " + " | ".join("---" for _ in rows[0]) + " |")
        for row in rows[1:]:
            lines.append("| " + " | ".join(cell(c) for c in row) + " |")
        return "\n".join(lines)

    result = []
    try:
        if col_xs:
            settings = {
                'vertical_strategy':       'explicit',
                'horizontal_strategy':     'lines',
                'explicit_vertical_lines': col_xs,
                'snap_tolerance':          3,
            }
            for tobj in page.find_tables(table_settings=settings):
                rows = tobj.extract()
                if quality_check(rows):
                    md = format_table(rows)
                    if md:
                        result.append((tobj.bbox, md))
        if not result:
            settings = {
                'vertical_strategy':   'lines',
                'horizontal_strategy': 'lines',
            }
            for tobj in page.find_tables(table_settings=settings):
                rows = tobj.extract()
                if quality_check(rows):
                    md = format_table(rows)
                    if md:
                        result.append((tobj.bbox, md))
    except Exception:
        pass
    return result


def analyse_pages(pdf_path):
    try:
        from pdfminer.high_level import extract_pages
        from pdfminer.layout import LAParams, LTTextBox, LTFigure, LTCurve
    except ImportError:
        print("⛔ pdfminer.six not installed. Run: pip install pdfminer.six", file=sys.stderr)
        sys.exit(1)
    laparams = LAParams(
        line_overlap=0.5, char_margin=2.0, line_margin=0.5,
        word_margin=0.1, boxes_flow=0.5, detect_vertical=False, all_texts=False
    )
    result = {}
    for page_num, layout in enumerate(extract_pages(pdf_path, laparams=laparams), 1):
        texts, figures, curves = [], [], []
        for el in layout:
            if isinstance(el, LTTextBox):
                t = el.get_text().strip()
                if t:
                    texts.append((t, (el.y0 + el.y1) / 2, el.x0, el.x1))
            elif isinstance(el, LTFigure):
                figures.append((el.x0, el.y0, el.x1, el.y1))
            elif isinstance(el, LTCurve):
                curves.append(el)
        h_lines = [c for c in curves if (c.y1 - c.y0) < 3 and (c.x1 - c.x0) > 50]
        v_lines = [c for c in curves if (c.x1 - c.x0) < 3 and (c.y1 - c.y0) > 30]
        _has_table = False
        if len(h_lines) >= 2 and len(v_lines) >= 2:
            for base in h_lines:
                aligned = [h for h in h_lines
                           if abs(h.x0 - base.x0) <= 10 and abs(h.x1 - base.x1) <= 10]
                if len(aligned) >= 2:
                    aligned_sorted = sorted(aligned, key=lambda h: h.y0)
                    min_spacing = min(aligned_sorted[i+1].y0 - aligned_sorted[i].y1
                                     for i in range(len(aligned_sorted) - 1))
                    if min_spacing >= 3:
                        h_x_span = (min(h.x0 for h in aligned), max(h.x1 for h in aligned))
                        v_crossing = [v for v in v_lines
                                     if h_x_span[0] - 5 <= (v.x0 + v.x1) / 2 <= h_x_span[1] + 5]
                        if len(v_crossing) >= 2:
                            _has_table = True
                            break
        result[page_num] = {
            'texts':     texts,
            'figures':   figures,
            'height':    layout.height,
            'has_table': _has_table,
        }
    return result


def main():
    try:
        import pdfplumber as pdfplumber_mod
        HAS_PDFPLUMBER = True
    except ImportError:
        HAS_PDFPLUMBER = False
        print("[chorus-pdf] ⚠️  pdfplumber not available — vector tables will not be reconstructed",
              file=sys.stderr)

    print(f"[chorus-pdf] Text mode — {PDF_PATH}", file=sys.stderr)
    page_data = analyse_pages(PDF_PATH)
    plumber_pdf = pdfplumber_mod.open(PDF_PATH) if HAS_PDFPLUMBER else None

    parts = []
    fig_pages    = 0
    total_tables = 0

    for page_num in sorted(page_data):
        pdata = page_data[page_num]
        blocks, has_figure, has_table, page_height = \
            pdata['texts'], bool(pdata['figures']), pdata['has_table'], pdata['height']
        elements = []

        table_bboxes = []
        if plumber_pdf and has_table:
            table_entries = extract_tables_from_page(plumber_pdf.pages[page_num - 1])
            for (tx0, t_top, tx1, t_bottom), md in table_entries:
                y_min = page_height - t_bottom
                y_max = page_height - t_top
                y_c   = (y_min + y_max) / 2
                table_bboxes.append((tx0, y_min, tx1, y_max))
                elements.append((y_c, md))
                total_tables += 1

        for (text, y_center, x0, x1) in blocks:
            x_center = (x0 + x1) / 2
            in_table = any(
                tb_x0 - 5 <= x_center <= tb_x1 + 5 and tb_y_min <= y_center <= tb_y_max
                for (tb_x0, tb_y_min, tb_x1, tb_y_max) in table_bboxes
            )
            if in_table:
                continue
            elements.append((y_center, text))

        if has_figure:
            elements.append((0, FIGURE_PLACEHOLDER))
            fig_pages += 1

        elements.sort(key=lambda e: e[0], reverse=True)
        body = "\n\n".join(c for (_, c) in elements)
        parts.append(f"=== PAGE {page_num} ===\n{body}\n=== END PAGE {page_num} ===")

    if plumber_pdf:
        plumber_pdf.close()

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n\n".join(parts))

    print(f"[chorus-pdf] ✅ {len(page_data)} pages extracted, {total_tables} table(s)", file=sys.stderr)
    if fig_pages:
        print(f"[chorus-pdf]    {fig_pages} page(s) contain figures — use --hybrid or --auto to extract them",
              file=sys.stderr)
    print(f"[chorus-pdf] Written to {OUTPUT_PATH}", file=sys.stderr)


if __name__ == "__main__":
    main()
